apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: k-s-skaffold
build:
  artifacts:
    - image: dockerfile-image
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
portForward:
  - resourceType: service
    resourceName: dockerfile-image
    port: 3000
